# Generated by Django 5.1.1 on 2024-09-16 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
                ('role', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('mode_of_transport', models.CharField(choices=[('C', 'CAR'), ('B', 'BIKE'), ('S', 'SHUTTLE')], default='S', max_length=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.organization')),
            ],
        ),
    ]
